import { Open_Sans } from 'next/font/google';
import './globals.css';
import AuthContext from '../context/AuthContext';
import Navbar from '../components/Navbar';
import SWRConfigContext from '../context/SWRConfigContext';
const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata = {
  title: {
    default: 'Instantgram',
    template: 'Instantgrram | %s',
    description: 'Instantgram Photos | %s',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={openSans.className}>
      <body className='w-full  overflow-auto mx-auto no-scrollbar bg-neutral-50'>
        <AuthContext>
          <header className='sticky   top-0 bg-white z-10 border-b '>
            <div className='max-w-screen-xl mx-auto'>
              <Navbar />
            </div>
          </header>

          <main className='flex w-full justify-center max-w-screen-xl mx-auto'>
            <SWRConfigContext> {children} </SWRConfigContext>
          </main>
        </AuthContext>
      </body>
    </html>
  );
}
