import { Open_Sans, Open_Sans } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={openSans.className}>
      <body className='w-full max-w-screen-xl overflow-auto mx-auto'>
        <header className='sticky top-0 bg-white z-10 border-b'>
          <Navbar />
        </header>
        <main> {children}</main>
      </body>
    </html>
  );
}
